# Generated by Django 5.0.1 on 2024-04-01 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bii', '0002_product_is_sale_product_sale_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_sale',
            new_name='on_sale',
        ),
    ]
