# Generated by Django 5.0.1 on 2024-04-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bii', '0003_rename_is_sale_product_on_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, default='', max_length=550, null=True),
        ),
    ]
